all:
	./compile
	@rm -f \
		*.aux **/*.aux \
		*.log **/*.log \
		*.bbl **/*.bbl \
		*.blg **/*.blg \
		*.toc **/*.toc \
		*.out **/*.out \
		*.idx **/*.idx \
		*.synctex.gz **/*.synctex.gz \
		*.snm **/*.snm \
		*.nav **/*.nav \
		*.dvi **/*.dvi \
		*.ent 
fast:
	pdflatex	main.tex

clean:
	rm -f \
		*.aux **/*.aux \
		*.log **/*.log \
		*.bbl **/*.bbl \
		*.blg **/*.blg \
		*.toc **/*.toc \
		*.out **/*.out \
		*.idx **/*.idx \
		*.synctex.gz **/*.synctex.gz \
		*.snm **/*.snm \
		*.nav **/*.nav \
		*.dvi **/*.dvi \
		*.ent 
